[versions]
accessibilityTestFramework = "4.1.1"
activityCompose = "1.12.2"
appcompat = "1.7.1"
appUpdate = "2.1.0"
browser = "1.9.0"
constraintlayout = "2.2.1"
converterMoshi = "3.0.0"
coreKtx = "1.17.0"
datastorePreferences = "1.2.0"
espressoCore = "3.7.0"
espressoLibraryKotlin = "2023.9.01"
firebaseBom = "34.7.0"
firebaseCrashlyticsGradle = "3.0.6"
googleServices = "4.4.4"
gradle = "8.13.2"
hiltAndroidGradlePlugin = "2.57.2"
hiltAndroidTesting = "2.57.2"
hiltCompiler = "1.3.0"
junit = "4.13.2"
junitVersion = "1.3.0"
kotlin = "2.3.0"
kotlinGradlePlugin = "2.1.20"
kotlinxCoroutinesAndroid = "1.10.2"
kotlinxCoroutinesCore = "1.10.2"
kotlinxSerializationJson = "1.9.0"
ksp = "2.3.4"
ktlint = "14.0.1"
legacySupportV4 = "1.0.0"
lifecycleExtensions = "2.2.0"
lifecycleLivedataKtx = "2.10.0"
lifecycleViewmodelCompose = "2.10.0"
loggingInterceptor = "5.3.2"
material3 = "1.13.0"
navigationDynamicFeaturesFragment = "2.9.6"
navigationFragmentKtx = "2.9.6"
navigationSafeArgsGradlePlugin = "2.9.6"
navigationTesting = "2.9.6"
navigationUiKtx = "2.9.6"
okhttp = "5.3.2"
orchestrator = "1.6.1"
perfPlugin = "2.0.2"
playServicesLocation = "21.3.0"
retrofit = "3.0.0"
retrofit2KotlinxSerializationConverter = "1.0.0"
roomCompiler = "2.8.4"
roomKtx = "2.8.4"
roomRuntime = "2.8.4"
rules = "1.7.0"
runner = "1.7.0"
vicoCore = "2.4.1" # Leave for now, resource linking issue with updated version, requires investigation.
viewpager2 = "1.1.0"

[libraries]
accessibility-test-framework = { module = "com.google.android.apps.common.testing.accessibility.framework:accessibility-test-framework", version.ref = "accessibilityTestFramework" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
adaptive = { module = "androidx.compose.material3.adaptive:adaptive" }
app-update = { module = "com.google.android.play:app-update", version.ref = "appUpdate" }
app-update-ktx = { module = "com.google.android.play:app-update-ktx", version.ref = "appUpdate" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
browser = { module = "androidx.browser:browser", version.ref = "browser" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "converterMoshi" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
espresso-library-kotlin = { module = "com.github.JoshLudahl:espresso-library-kotlin", version.ref = "espressoLibraryKotlin" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
feature-delivery = { module = "com.google.android.play:feature-delivery", version.ref = "appUpdate" }
feature-delivery-ktx = { module = "com.google.android.play:feature-delivery-ktx", version.ref = "appUpdate" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-crashlytics-gradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "firebaseCrashlyticsGradle" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-database = { module = "com.google.firebase:firebase-database" }
firebase-perf = { module = "com.google.firebase:firebase-perf" }
google-services = { module = "com.google.gms:google-services", version.ref = "googleServices" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroidGradlePlugin" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroidGradlePlugin" }
hilt-android-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hiltAndroidGradlePlugin" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hiltAndroidTesting" }
hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltCompiler" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinGradlePlugin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
legacy-support-v4 = { module = "androidx.legacy:legacy-support-v4", version.ref = "legacySupportV4" }
lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycleExtensions" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleLivedataKtx" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
material-icons-core = { module = "androidx.compose.material:material-icons-core" }
material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
material3View = { module = "com.google.android.material:material", version.ref = "material3" }
material3Compose = { module = "androidx.compose.material3:material3" }
navigation-dynamic-features-fragment = { module = "androidx.navigation:navigation-dynamic-features-fragment", version.ref = "navigationDynamicFeaturesFragment" }
navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
navigation-safe-args-gradle-plugin = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigationSafeArgsGradlePlugin" }
navigation-testing = { module = "androidx.navigation:navigation-testing", version.ref = "navigationTesting" }
navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationUiKtx" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
orchestrator = { module = "androidx.test:orchestrator", version.ref = "orchestrator" }
perf-plugin = { module = "com.google.firebase:perf-plugin", version.ref = "perfPlugin" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit2-kotlinx-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit2KotlinxSerializationConverter" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomCompiler" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomKtx" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
rules = { module = "androidx.test:rules", version.ref = "rules" }
runner = { module = "androidx.test:runner", version.ref = "runner" }
runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata" }
runtime-rxjava2 = { module = "androidx.compose.runtime:runtime-rxjava2" }
ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }
vico-core = { module = "com.patrykandpatrick.vico:core", version.ref = "vicoCore" }
vico-views = { module = "com.patrykandpatrick.vico:views", version.ref = "vicoCore" }

[plugins]
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
firebase-crashlytics = {id = "com.google.firebase.crashlytics"}
firebase-perf = { id = "com.google.firebase.firebase-perf" }
google-services = { id = "com.google.gms.google-services" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
